### PR TITLE
Support multipart/form-data POST requests

### PR DESCRIPTION
**Pull request by gaborcsardi**
This is not final, just wanted to see if you like it. It works like this:

```js
var papi = require('papi');
var client = papi.Client('http://httpbin.org');

var buf = Buffer.from('this is a buffer');

var cb = function(err, res) {
  if (err) console.log(err);
  if (res) console.log(res.body);
}

var opts = {
  path: '/post',
  multipart: {
    'file0': buf,
    'json': '{"parameter": [{"name":"id", "value":"123"}, {"name": "blah", "file": "file0"}]}',
    'foobar': {
      'Content-Type': 'image/custom',
      body: buf
    }
  }
}

client._post(opts, cb)
```

### CODE REVIEW

**Comment by silas** [comment]
Yeah, direction seems good. I'd want to read up on multipart encoding a bit more before doing a review, bur I'd be nice to get this implemented here and in node-jenkins.

**Comment by gaborcsardi** [comment]
Thanks!  Yeah, multipart encoding is a bit messy. 

E.g. one thing is that ideally we should send an `Expect: 100-continue` header.  (E.g. http://www.iandennismiller.com/posts/curl-http1-1-100-continue-and-multipartform-data-post.html)
For Jenkins it should matter much, unless the Jenkins URL is redirected.

**Comment by gaborcsardi** [comment]
Added tests.

**Comment by silas** [comment]
Hey @gaborcsardi, thanks for the PR and work.

 I decided I didn't want to maintain a version of mutipart form encoding in papi. I implemented `form-data` support in the `jenkins` client, see https://github.com/silas/node-jenkins/commit/4cad1dad59ea1796a733d61934ab2ef85809799d

**Pull request closed without merging**
