### PR TITLE
support pre-encoded (string) query params

### PR DESCRIPTION
**Pull request by liquidninja24**

### CODE REVIEW

**Comment by liquidninja24** [comment]
Main reason for adding this is to support alternate query string encodings.

We have an issue right now where a ruby service is expecting arrays to come through as `test[]=1&test[]=2` rather than `test=1&test=2`. The `querystring` module doesn't support that, so i'm encoding the params in `node-clients` using the `qs` module and passing the query through that way.

**Comment by silas** [comment]
It's not obvious, but papi allows you to override the form encoder/decoder.

``` javascript
var papi = require('papi');
var qs = require('qs');

var form = {};

form.encode = function(data) {
  return papi.codecs.text.encode(qs.stringify(data));
};

form.decode = function(data) {
  return qs.parse(papi.codecs.text.decode(data));
};

var client = new papi.Client({
  baseUrl: 'http://localhost:8000',
  encoders: { 'application/x-www-form-urlencoded': form.encode },
  decoders: { 'application/x-www-form-urlencoded': form.decode },
});

client._get({ path: '/test', query: { a: ['b', 'c'] } }, function(err) {
  if (err) throw err;
});
```

I just pushed v0.23 which exposes the text encoder/decoder so you won't need to re-implement that.

This seem like an ok solution?

**Comment by liquidninja24** [comment]
So, this encoding is being done inside of a method within our node-clients module, which has an instance of papi passed into it. I don't think we're able to / want to create a new instance of the client for this single call. Is there a way to override the encoding without initializing a new instance?

Also, what about allowing a function to be passed as the query property like we do for `body`, instructing papi not to encode the parameter any further?

**Comment by silas** [comment]
Generally form encoding is done consistently across the entire service, are different routes within the service handling encoding differently? If not why not just change it for the entire service?

I'm not opposed to allowing a raw query string, just curious.

**Comment by liquidninja24** [comment]
I was able to solve the problem using your above example when initializing the client on the service level. Thanks for the help, Silas!

**Pull request closed without merging**
